[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
api_model = { path = "../api_model" }
cli_handler = { path = "../cli_handler" }
clap = { version = "4.5", features = ["derive"] }
chrono = "0.4.42"
unicode-width = "0.1"
