[package]
name = "api_model"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
bytes = "1.10.1"
lexical-core = "1.0.6"
bincode = "1.3.3"
chrono = "0.4.42"
